### ISSUE TITLE
don't require global elm install "npm -g"

### ISSUE THREAD

**Issue by raould** [elm-lang/core#880]
I prefer to avoid doing global npm installs whenever possible. So I did "npm install elm" but I get the [dreaded error](https://github.com/elm-lang/core/issues/787). It would be nice if elm could somehow work in a project-local setting.

```
$ which elm
./node_modules/.bin/elm
$ elm
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/user/Documents/x/node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by evancz** [comment]
Can you retarget this issue to https://github.com/elm-lang/elm-platform which is where the installer code lives? The `npm` installer is managed by @rtfeldman, so he'd know more about what might be going on in this case. Nonetheless, the place to continue this discussion is on `elm-platform`!
